### ISSUE TITLE
阅读模式拓展

### ISSUE THREAD

**Issue by 7-bit11** [fluttercandies/flutter_novel#1]
### Platforms

Android, iOS

### Description

阅读模式可以分上下或者是翻页的那种。

### Why

反馈

**Comment by Liloupar** [comment]
仿真翻页+1

**Comment by Liloupar** [comment]
已经实现了么 没找到啊..

**Comment by 7-bit11** [comment]
理解错误了。。现在只有一个左右切换翻页的效果，后续会新增上下翻页效果
